github/globalmaintainersummit.github.com

components/CustomLink.vue
pages/index.vue

Add `CustomLink` component.
Since all we have are links, I've decided not to create a `CustomButton` component to avoid confusion. When we want the link to look like a button, we can do that just by a passing a `button` property.
https://user-images.githubusercontent.com/39853718/113142844-ab4aff00-922b-11eb-8afc-1cd9cd176d3d.mov

feat: add custom link

---

assets/scss/mixins/main.scss
components/FloatingCard.vue
components/Lead.vue
components/ProjectPill.vue
components/Projects.vue
components/common/Link.vue
content/home.json
nuxt.config.js
pages/index.vue

This PR adds a new section component `Projects` that contains a series of `ProjectPills` components that are rendered based on the content at `projects` array inside `content/home.json`

feat(home): Add projects section

---

nuxt.config.js

This PR fixes the social card missing image due to the name not being updated.

fix(meta): Social Card name update.

---

content/home.json

Sorry if I messed this up (might have broken the paragraphs, too) ; trying at least :)

Updating main text

---

content/home.json

Renaming auto-added calendar event

"event" --> "summit"

---

package-lock.json
package.json

I checked the dependencies with `npm outdated` and some of them were really behind, so I did a general upgrade.

chore: update dependencies due to security issues

---

.github/CODEOWNERS
.github/dependabot.yml

This adds the dependabot configuration file for `npm` and also add a `CODEOWNERS` file to get automatic review requests.

chore: add dependabot

---

.github/workflows/build-and-deploy-workflow.yml
.gitignore
lighthouserc.js

This adds Lighthouse CI to the project, so we can monitor the performance impact of our development.

build: add lighthouse CI

---

assets/scss/mixins/main.scss
assets/scss/variables/_colors.scss
assets/scss/variables/_layout.scss
assets/scss/variables/_media-queries.scss
components/Footer.vue
components/Hamburguer.vue
components/TopNav.vue
components/common/Link.vue
cypress/integration/layout.spec.js
layouts/default.vue
package-lock.json
package.json
pages/maintainers.vue
pages/schedule.vue
stylelint.config.js

feat(navigation): Add TopBar component

---

components/common/Link.vue

feat(links): Add link underline wave.

---

assets/svg/bg_pills/graphic_pills.svg
components/common/Grid.vue
components/common/SwitchButton.vue
pages/maintainers.vue
pages/projects.vue

- https://deploy-preview-69--gh-maintainers.netlify.app/projects/
- https://deploy-preview-69--gh-maintainers.netlify.app/maintainers/

feat(ui): Add simple switch button component

---

components/FollowEvent.vue
components/Footer.vue
components/codeOfConduct/List.vue
components/codeOfConduct/Main.vue
components/codeOfConduct/Pill.vue
content/2021/pages/code-of-conduct.json
content/home.json
cypress/integration/code-of-conduct.spec.js
pages/code-of-conduct.vue
pages/maintainers.vue
pages/projects.vue
pages/schedule.vue
stylelint.config.js

- Adds code of conduct page.
- Adds the social media mixin to all the pages.
- Update `FollowEvent` component to adjust padding for mobile.
- [Task](https://app.clickup.com/t/jd3839)
- [Design](https://marvelapp.com/prototype/g6hc7ee/screen/78754092/handoff)

feat: add code of conduct page

---

assets/scss/_global.scss
assets/scss/variables/_colors.scss
components/MaintainerCard.vue
components/common/CustomButton.vue
components/home/Newsletter.vue
content/2021/pages/home/index.json
pages/index.vue

feat(newsletter): Add form styles

---

content/2021/pages/home/index.json
cypress/integration/home.spec.js
pages/index.vue

This fixes the home's maintaners cta button.

fix: maintainers cta button

---

pages/index.vue

This fixes a minor issue with the button visibility.
Before:
After:

fix: maintainers button cropped

---

components/home/Newsletter.vue
cypress/integration/home.spec.js

This adds the form logic to subscribe to the newsletter and its corresponding tests.

feat: add subscribe form logic

---

assets/scss/variables/_colors.scss
components/TopNav.vue
layouts/default.vue

- Make nav sticky when user scrolls up.
- Adds missing `header` element.
- [Task](https://app.clickup.com/t/kd6q8a)

feat: make nav sticky

---

content/2021/pages/schedule/day-1.json

Updating schedule

---

content/2021/pages/schedule/day-1.json

Remove a person from the schedule as they don't have the profile (json file) filled.

Release: fix schedule

---

content/2021/pages/home/index.json

I think the `it` is incorrect, which makes the sentence seem weird.
- I don't think it's worth opening an issue.
None.
(optional)
* https://google.com/search?q=%22what+is+it+possible+to+automate%22
* https://google.com/search?q=%22what+is+possible+to+automate%22
None

Improve wording in home page

---

content/2021/pages/schedule/day-1.json
content/2021/pages/schedule/day-2.json
content/2021/shared/maintainers/ifiokjr.json
content/2021/shared/maintainers/zkoppert.json

This PR updates the last two talk titles on day 2.

Update last two day two talks

---

app.html
components/home/Newsletter.vue

Fix some console errors that were causing the page to misbehave in netlify:
- `jquery` is `undefined` error.
- The client-side rendered virtual DOM tree is not matching server-rendered.
- [Task](https://app.clickup.com/t/m3ab2f)

fix: console errors

---

components/common/SwitchButton.vue
components/schedule/Slot.vue
cypress/integration/schedule.spec.js
utils/date-utils.js

- Display just the city in the time zone switch.
- Fix switch font color purple on click.
- [Task](https://app.clickup.com/t/m56j0t)

feat: format time zone

---

assets/scss/_global.scss
layouts/default.vue

Add page transitions for a smother experience.
- [Task](https://app.clickup.com/t/m57828)

feat: add page transitions

---

components/home/HeroLive.vue

Update video id for the second day.
- [Task](https://app.clickup.com/t/m3d6c9)

chore: update video for day 2

---

components/home/Hero.vue

(required) Please include any relevant details about this Pull Request, with a focus on:
- _What_ does it fix.
- Event live flag (revert 23068363a907c27df654475072849e1582afcda7)

Make it so event is not live
